# Generated by Django 2.2.7 on 2020-01-02 19:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='tagsAndKeywords',
            field=jsonfield.fields.JSONField(),
        ),
    ]
