# Generated by Django 2.2.7 on 2020-01-02 19:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20200102_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='tagsAndKeywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
