# Generated by Django 2.2.7 on 2020-01-02 20:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_auto_20200102_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='address',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
