# Generated by Django 2.2.7 on 2020-01-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_auto_20200102_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='tagsAndKeywords',
        ),
    ]
