# Generated by Django 2.2.7 on 2020-01-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0015_organizationprofile_tagsandkeywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='address',
            field=models.TextField(),
        ),
    ]
