# Generated by Django 2.2.7 on 2020-01-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0020_auto_20200102_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='tagsAndKeywords',
            field=models.TextField(),
        ),
    ]
