# Generated by Django 2.2.7 on 2020-01-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0022_auto_20200104_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
