# Generated by Django 2.2.7 on 2020-01-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0026_auto_20200106_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='tagsAndKeywords', to='finder.OrganizationProfile'),
        ),
    ]
