# Generated by Django 2.0 on 2020-01-12 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0028_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('participant_img_url', models.CharField(blank=True, max_length=200, null=True)),
                ('org_type', models.CharField(blank=True, max_length=200, null=True)),
                ('org_icon_url', models.CharField(blank=True, max_length=200, null=True)),
                ('org_url', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finder.Location')),
            ],
        ),
        migrations.CreateModel(
            name='TagP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='participants',
            name='tags',
            field=models.ManyToManyField(related_name='participants', to='finder.TagP'),
        ),
    ]
