# Generated by Django 2.0 on 2020-01-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0031_auto_20200112_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagp',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='participants', to='finder.Participants'),
        ),
    ]
