# Generated by Django 2.0 on 2020-01-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0032_auto_20200113_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagp',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='tagsAndKeywordsP', to='finder.Participants'),
        ),
    ]
