# Generated by Django 2.2 on 2020-01-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0033_auto_20200116_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(max_length=32)),
            ],
        ),
    ]
