# Generated by Django 2.2 on 2020-01-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0034_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='t',
        ),
    ]
