# Generated by Django 2.2.7 on 2020-04-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0035_delete_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_part',
            field=models.ManyToManyField(blank=True, related_name='Part_Event', to='finder.Participants'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_upcoming',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='collaborations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='consorsiumRoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='dataStatus',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='numberOfProjects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
