# Generated by Django 2.2.7 on 2020-05-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0036_auto_20200423_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalID', models.IntegerField(unique=True)),
                ('indexID', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapIDsB2match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalID', models.IntegerField(unique=True)),
                ('indexID', models.IntegerField(unique=True)),
            ],
        ),
    ]
