# Generated by Django 2.2.10 on 2020-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0038_mapidsb2matchupcoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccm2Id', models.IntegerField(unique=True)),
                ('deadlineDatesLong', models.IntegerField()),
                ('type', models.IntegerField()),
                ('identifier', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('sumbissionProcedure', models.CharField(max_length=200)),
                ('callTitle', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CallTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('calls', models.ManyToManyField(blank=True, related_name='tagsAndKeywords', to='finder.Call')),
            ],
        ),
    ]
