# Generated by Django 2.2.10 on 2020-05-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0039_call_calltag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='deadlineDatesLong',
            new_name='deadlineDate',
        ),
    ]
