# Generated by Django 2.2.10 on 2020-05-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0041_auto_20200526_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores',
            old_name='RSE',
            new_name='RES',
        ),
    ]
