# Generated by Django 2.2.10 on 2020-05-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0043_updatesettings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatesettings',
            name='b2match_last_update',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='updatesettings',
            name='eu_last_update',
            field=models.IntegerField(),
        ),
    ]
