# Generated by Django 2.2.10 on 2020-05-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0044_auto_20200526_1648'),
        ('finder', '0042_auto_20200526_1706'),
    ]

    operations = [
    ]
