# Generated by Django 2.2.10 on 2020-05-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0045_merge_20200526_2045'),
        ('finder', '0045_merge_20200526_1837'),
    ]

    operations = [
    ]
