# Generated by Django 2.2.10 on 2020-05-26 17:54

from django.db import migrations, models
import finder.models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0045_merge_20200526_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='Association_Agency',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Austria',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Company',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Czech_Republic',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Denmark',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Finland',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='France',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Germany',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Ireland',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Israel',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Italy',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Norway',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Others',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Portugal',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='RES',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='R_D_Institution',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Spain',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Start_Up',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Switzerland',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Turkey',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Ukranie',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='United_Kingdom',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='scores',
            name='University',
            field=models.FloatField(default=0, null=True, validators=[finder.models.validate_even]),
        ),
    ]
