# Generated by Django 2.2.10 on 2020-06-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0047_auto_20200531_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsForAlerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, unique=True)),
                ('event_url', models.CharField(max_length=200)),
                ('event_score', models.FloatField()),
            ],
        ),
    ]
