# Generated by Django 2.2.10 on 2020-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0048_eventsforalerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_part',
            field=models.ManyToManyField(related_name='Part_Event', to='finder.Participants'),
        ),
    ]
