# Generated by Django 2.2.10 on 2020-07-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0051_auto_20200623_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsforalerts',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
